<?php

/**
 * @file
 * Contains birthday_submissions.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function birthday_submissions_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the birthday_submissions module.
    case 'help.page.birthday_submissions':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Form to collect birthday submissions') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function birthday_submissions_theme() {
  return [
    'birthday_submissions' => [
      'render element' => 'children',
    ],
  ];
}
